version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    build:
      context: .
    restart: always
    entrypoint: /src/entrypoint.sh
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  celery_worker:
    build:
      context: .
    command: poetry run celery -A celery_app.worker worker --loglevel=info
    volumes:
      - .:/backend
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres-data:
    driver: local
